global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: "muffin-wallet"
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
  - targets: ["muffin-wallet.ru"]
